Repository sberdevices/plasma, pull requests merged in 2021-09, with the labels that each got.

#675 feat(plasma-ui): value format for `Stepper` added
  packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx
  packages/plasma-ui/src/components/Stepper/Stepper.tsx
  packages/plasma-ui/src/components/Stepper/StepperValue.tsx
Labels: TESTED

#709 fix(plasma-tokens-b2c): Confusing `paragraph` and `inverse` colors in…
  packages/plasma-tokens-b2c/design-language/src/DesignLanguage.ts
Labels: TESTING

#662 chore(plasma-ui, plasma-web): knobs to controls migration - web - part 4
  packages/plasma-web/src/components/Badge/Badge.stories.tsx
  packages/plasma-web/src/components/Image/Image.stories.tsx
  packages/plasma-web/src/components/Price/Price.stories.tsx
  packages/plasma-web/src/components/Spinner/Spinner.stories.tsx
  packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx
Labels: RFT

#652 chore(plasma-ui, plasma-web): knobs to controls migration - web - part 2
  packages/plasma-web/src/components/Notification/Notification.stories.tsx
  packages/plasma-web/src/components/PaginationDots/PaginationDots.stories.tsx
  packages/plasma-web/src/components/Progress/Progress.stories.tsx
  packages/plasma-web/src/components/Radiobox/Radiobox.stories.tsx
Labels: RFT

#651 chore(plasma-ui, plasma-web): knobs to controls migration - web - part 1
  packages/plasma-web/src/components/Button/Button.stories.tsx
  packages/plasma-web/src/components/Carousel/Carousel.stories.tsx
  packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
  packages/plasma-web/src/components/Modal/Modal.stories.tsx
Labels: RFT

#784 fix: Display `inline-flex` for `Badge`
  packages/plasma-core/src/components/Badge/Badge.tsx
Labels: TESTING

#703 fix(plasma-web): Collision of `Button` and global custom css
  packages/plasma-core/src/components/Button/Button.tsx
  packages/plasma-core/src/mixins/applyView.ts
  packages/plasma-web/.storybook/preview.js
  packages/plasma-web/src/components/Button/Button.stories.tsx
  packages/plasma-web/src/components/Button/Button.tsx
Labels: TESTED

#716 fix(plasma-ui): Added `coverGradient` prop to `CardContent`
  packages/plasma-ui/src/components/Card/Card.stories.tsx
  packages/plasma-ui/src/components/Card/CardContent.tsx
Labels: TESTED
