Repository sberdevices/plasma, pull requests merged in 2021-12, with the labels that each got.

#955 feat(plasma-ui): Add default value in `Slider` component if theme context is undefined
  packages/plasma-ui/src/components/Slider/SliderBase.tsx
Labels: UI (Canvas Apps), TESTED

#932 fix(plama-web): Added possibility to specify a value type in `Select`
  packages/plasma-web/src/components/Select/Select.tsx
  packages/plasma-web/src/components/Select/withMultiSelect.tsx
  packages/plasma-web/src/components/Select/withSingleSelect.tsx
Labels: TESTED, B2B/E

#967 fix(palsma-b2c): preview gallery data contracts
  packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.tsx
  packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItems.tsx
Labels: B2C

#950 fix: Set Underline to uppercase
  cypress/snapshots/b2c/components/Typography/TypographyCoreBase.component-test.tsx/plasma-core Typography -- Typography with breakWord.snap.png
  cypress/snapshots/b2c/components/Typography/TypographyCoreBase.component-test.tsx/plasma-core Typography -- Typography without breakWord.snap.png
  cypress/snapshots/b2c/components/Typography/TypographyCoreBase.component-test.tsx/plasma-core Typography -- Typography.snap.png
  cypress/snapshots/ui/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography with breakWord.snap.png
  cypress/snapshots/ui/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography without breakWord.snap.png
  cypress/snapshots/ui/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography.snap.png
  cypress/snapshots/web/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography with breakWord.snap.png
  cypress/snapshots/web/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography without breakWord.snap.png
  cypress/snapshots/web/components/Typography/TypographyBase.component-test.tsx/plasma-core Typography -- Typography.snap.png
  packages/plasma-core/src/components/Typography/Underline/index.ts
Labels: Components, UI (Canvas Apps), TESTED, B2B/E, B2C

#1000 feat(b2c): add SSRProvider
  packages/plasma-b2c/src/components/SSRProvider/index.ts
  packages/plasma-b2c/src/index.ts
Labels: Tests

#958 fix(plasma-ui): Prevent `Radiobox`'s & `Checkbox`'s trigger from squeeze
  cypress/snapshots/ui/components/Checkbox/CheckboxBase.component-test.tsx/plasma-core Checkbox -- squeezes.snap.png
  cypress/snapshots/ui/components/Radiobox/RadioboxBase.component-test.tsx/plasma-core Radiobox -- squeezes.snap.png
  packages/plasma-core/src/components/Basebox/Basebox.tsx
  packages/plasma-core/src/components/Checkbox/Checkbox.component-test.tsx
  packages/plasma-core/src/components/Radiobox/Radiobox.component-test.tsx
  packages/plasma-ui/src/components/Checkbox/Checkbox.tsx
  packages/plasma-ui/src/components/Radiobox/Radiobox.stories.tsx
  packages/plasma-ui/src/components/Radiobox/Radiobox.tsx
Labels: TESTED

#1013 test(plasma-b2c): Add tests and snapshots for `Editable` component
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- empty.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- onBlur and onFocus.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- onChange.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- onPaste.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- simple.snap.png
  packages/plasma-b2c/src/components/Editable/Editable.component-test.tsx
Labels: Tests

#1015 test(plasma-b2c): Add tests and snapshots for `Slider` component
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- _disabled.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- double.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- drag and drop with double.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- drag and drop with single.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- drag and drop without onChange.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-b2c Slider -- simple.snap.png
  packages/plasma-b2c/src/components/Slider/Slider.component-test.tsx
Labels: Tests

#1012 test(plasma-b2c): Add tests and snapshots for `Upload` component
  cypress/snapshots/b2c/components/Upload/Upload.component-test.tsx/plasma-b2c Upload -- upload dnd from fixture.snap.png
  packages/plasma-b2c/src/components/Upload/Upload.component-test.tsx
  packages/plasma-b2c/src/components/Upload/utils.ts
Labels: Tests

#1007 fix(plasma-ui): Add scroll fix for `Picker` component
  packages/plasma-ui/src/components/Pickers/Picker.tsx
Labels: UI (Canvas Apps)

#953 ci: Versionate docs
  .eslintignore
  .github/workflows/release.yml
  .github/workflows/versionate-docs.yml
  actions/versionate-docs/.gitignore
  actions/versionate-docs/.npmrc
  actions/versionate-docs/action.yml
  actions/versionate-docs/jest.config.js
  actions/versionate-docs/jest.config.ts
  actions/versionate-docs/package-lock.json
  actions/versionate-docs/package.json
  actions/versionate-docs/src/commits.test.ts
  actions/versionate-docs/src/commits.ts
  actions/versionate-docs/src/exec.ts
  actions/versionate-docs/src/fs.ts
  actions/versionate-docs/src/github.ts
  actions/versionate-docs/src/main.ts
  actions/versionate-docs/src/packages.ts
  actions/versionate-docs/src/utils.ts
  actions/versionate-docs/tsconfig.json
  lerna.json
  package-lock.json
  package.json
Labels: CI

#1021 test(plasma-ui): Add tests and snapshots for `Slider` component
  cypress/snapshots/ui/components/Slider/Slider.component-test.tsx/plasma-ui Slider -- _disabled.snap.png
  cypress/snapshots/ui/components/Slider/Slider.component-test.tsx/plasma-ui Slider -- drag and drop with double.snap.png
  cypress/snapshots/ui/components/Slider/Slider.component-test.tsx/plasma-ui Slider -- drag and drop with single.snap.png
  cypress/snapshots/ui/components/Slider/Slider.component-test.tsx/plasma-ui Slider -- drag and drop without onChange.snap.png
  packages/plasma-ui/src/components/Slider/Slider.component-test.tsx
Labels: Tests

#1016 fix(plasma-ui): Set `HeaderArrow` full height
  packages/plasma-ui/src/components/Header/HeaderArrow.tsx
Labels: TESTED
