Repository sberdevices/plasma, pull requests merged in 2021-11, with the labels that each got.

#921 chore(plasma-ui): fix sb card cover control
  packages/plasma-ui/src/components/Card/Card.stories.tsx
Labels: Plasma UI

#908 fix: Separate `Input`'s animation by b2b and b2c
  packages/plasma-core/src/components/TextField/TextField.tsx
  packages/plasma-ui/src/components/Field/Field.tsx
  packages/plasma-web/src/components/Field/Field.tsx
Labels: TESTED

#901 ci: Check for A11y with cypress-axe
  .gitignore
  cypress.json
  cypress/config/b2c-config.json
  cypress/config/ui-config.json
  cypress/config/web-config.json
  cypress/plugins/index.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: CI, Tests

#917 chore: Coverage for all packages
  .babelrc.js
  .github/workflows/cypress-ct.yml
  .gitignore
  cypress/plasma-b2c-coverage/.gitignore
  cypress/plasma-ui-coverage/.gitignore
  cypress/plasma-web-coverage/.gitignore
  cypress/plugins/index.ts
  cypress/support/index.ts
  nyc.config.js
  package-lock.json
  package.json
  packages/plasma-ui/src/components/Badge/Badge.component-test.tsx
  packages/plasma-ui/src/components/Button/Button.component-test.tsx
Labels: CI, Tests

#925 fix(plasma-web): prevent disabled select from opening
  cypress/snapshots/web/components/Select/Select.component-test.tsx/plasma-web Select -- disabled.snap.png
  packages/plasma-b2c/src/components/Select/SelectView.tsx
  packages/plasma-web/src/components/Select/Select.component-test.tsx
  packages/plasma-web/src/components/Select/Select.types.ts
  packages/plasma-web/src/components/Select/SelectDropdown.tsx
  packages/plasma-web/src/components/Select/SelectView.tsx
Labels: TESTED

#898 feat(plasma-ui-docs, plasma-web-docs): Added version indicator at the top
  website/plasma-ui-docs/docusaurus.config.js
  website/plasma-ui-docs/package.json
  website/plasma-ui-docs/versionsArchived.json
  website/plasma-web-docs/docusaurus.config.js
  website/plasma-web-docs/versionsArchived.json
Labels: Docs, TESTED

#933 fix(plasma-web): Add `Button`'s `warning` view
  packages/plasma-web/src/components/Button/Button.stories.tsx
  packages/plasma-web/src/components/Button/Button.tsx
Labels: TESTED, Plasma Web

#935 fix(plasma-tokens-web): Fix `Tooltip` & `Button` confusing `checked` …
  cypress/snapshots/b2c/components/Button/ButtonBase.component-test.tsx/plasma-core Button -- _view.snap.png
  cypress/snapshots/b2c/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- simple.snap.png
  packages/plasma-tokens-b2c/design-language/src/DesignLanguage.ts
Labels: RFT
