Repository sberdevices/plasma, pull requests merged in 2021-07, with the labels that each got.

#500 chore(plasma-ui): Change deviceKind through get param in iframe
  packages/plasma-ui/.storybook/preview.js
Labels: documentation

#517 fix(plasma-ui): Header back button position
  packages/plasma-ui/src/components/Header/HeaderBack.tsx
  packages/plasma-ui/src/components/Header/HeaderRoot.tsx
Labels: bug, components, plasma-ui

#583 fix(plasma-ui): huawei detection fix
  packages/plasma-ui/src/utils/deviceDetection.ts
Labels: TESTED
