Repository sberdevices/plasma, pull requests merged in 2022-01, with the labels that each got.

#1035 ci: Use `GH_TOKEN` to push versionate jsons
  .github/workflows/versionate-docs.yml
Labels: CI

#1029 fix(plasma-b2c,plasma-web): Add re-export for `Notification` component
  packages/plasma-b2c/src/components/Notification/index.tsx
  packages/plasma-web/src/components/Notification/index.tsx
Labels: TESTED

#1032 test(plasma-temple): ItemPage Spec
  cypress/snapshots/temple/pages/ItemPage/itemPage.component-test.tsx/ItemPage -- base test -- screen rendered.snap.png
  cypress/snapshots/temple/pages/ItemPage/itemPage.component-test.tsx/ItemPage -- render with custom card -- render list of custom card.snap.png
  cypress/support/commands.ts
  packages/plasma-temple/src/pages/ItemPage/components/ItemMainSection/ItemMainSection.tsx
  packages/plasma-temple/src/pages/ItemPage/itemPage.component-test.tsx
  packages/plasma-temple/src/pages/ItemPage/types.ts
Labels: Tests

#1037 feat(plasma-core): Make toasts stretch more then 50% of container
  cypress/snapshots/b2c/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- _position.snap.png
  cypress/snapshots/b2c/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- showToast.snap.png
  cypress/snapshots/b2c/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- two lines.snap.png
  cypress/snapshots/ui/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- _position.snap.png
  cypress/snapshots/ui/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- showToast.snap.png
  cypress/snapshots/ui/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- two lines.snap.png
  cypress/snapshots/web/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- _position.snap.png
  cypress/snapshots/web/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- showToast.snap.png
  cypress/snapshots/web/components/Toast/ToastBase.component-test.tsx/plasma-core Toast -- useToast -- two lines.snap.png
  packages/plasma-core/src/components/Toast/Toast.tsx
  packages/plasma-core/src/components/Toast/ToastBase.component-test.tsx
  packages/plasma-core/src/components/Toast/ToastController.tsx
Labels: UI (Canvas Apps), TESTED, B2B/E, B2C

#1045 fix(plasma-ui): `ActionButton`: Made `pin` not required again
  packages/plasma-ui/src/components/Button/ActionButton.tsx
Labels: UI (Canvas Apps), TESTING

#1056 fix(plasma-core): Add inherit cursor in label for `BaseBox` component
  packages/plasma-core/src/components/Basebox/Basebox.tsx
Labels: TESTED
