Repository sberdevices/plasma, pull requests merged in 2022-02, with the labels that each got.

#1057 fix(plasma-web, plasma-ui): `Basebox`: Hide input properly; tabIndex=…
  packages/plasma-core/src/components/Basebox/Basebox.tsx
  packages/plasma-ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/plasma-ui/src/components/Checkbox/Checkbox.tsx
  packages/plasma-ui/src/components/Radiobox/Radiobox.stories.tsx
  packages/plasma-ui/src/components/Radiobox/Radiobox.tsx
  packages/plasma-web/src/components/Checkbox/Checkbox.tsx
  packages/plasma-web/src/components/Radiobox/Radiobox.tsx
Labels: UI (Canvas Apps), TESTED, B2B/E, B2C

#1052 chore: Storybook: Added lang to make VoiceOver read russian text prop…
  packages/plasma-b2c/.storybook/preview.js
  packages/plasma-temple/.storybook/preview.js
  packages/plasma-web/.storybook/preview.js
Labels: TESTED

#1051 feat(plasma-icons): Add all devices icons
  packages/plasma-icons/src/Icon.assets/Devices.tsx
  packages/plasma-icons/src/Icon.assets/DevicesAlt1.tsx
  packages/plasma-icons/src/Icon.assets/Mobile.tsx
  packages/plasma-icons/src/Icon.assets/MobileAutorotate.tsx
  packages/plasma-icons/src/Icon.assets/PercentStroke.tsx
  packages/plasma-icons/src/Icon.assets/Phone.tsx
  packages/plasma-icons/src/Icon.assets/PhoneStroke.tsx
  packages/plasma-icons/src/Icon.assets/PhoneWiFi.tsx
  packages/plasma-icons/src/Icon.assets/PictureFilled.tsx
  packages/plasma-icons/src/Icon.assets/SberBoom.tsx
  packages/plasma-icons/src/Icon.assets/SberBoxTime.tsx
  packages/plasma-icons/src/Icon.assets/SberBoxTimeStroke.tsx
  packages/plasma-icons/src/Icon.assets/SberBoxTop.tsx
  packages/plasma-icons/src/Icon.assets/SberBoxTopFront.tsx
  packages/plasma-icons/src/Icon.assets/SberBoxTopStroke.tsx
  packages/plasma-icons/src/Icon.assets/SberPortal.tsx
  packages/plasma-icons/src/Icon.assets/SberPortalStroke.tsx
  packages/plasma-icons/src/Icon.assets/Tv.tsx
  packages/plasma-icons/src/Icon.assets/TvAlt1.tsx
  packages/plasma-icons/src/Icon.assets/TvChannel.tsx
  packages/plasma-icons/src/Icon.assets/TvChannelAlt1.tsx
  packages/plasma-icons/src/Icon.assets/TvMode.tsx
  packages/plasma-icons/src/Icon.assets/TvModeWiFi.tsx
  packages/plasma-icons/src/Icon.tsx
  packages/plasma-icons/src/Icons/IconDevicesAlt1.tsx
  packages/plasma-icons/src/Icons/IconMobile.tsx
  packages/plasma-icons/src/Icons/IconPhone.tsx
  packages/plasma-icons/src/Icons/IconPhoneStroke.tsx
  packages/plasma-icons/src/Icons/IconPhoneWiFi.tsx
  packages/plasma-icons/src/Icons/IconSberBoom.tsx
  packages/plasma-icons/src/Icons/IconSberBoxTime.tsx
  packages/plasma-icons/src/Icons/IconSberBoxTimeStroke.tsx
  packages/plasma-icons/src/Icons/IconSberBoxTop.tsx
  packages/plasma-icons/src/Icons/IconSberBoxTopFront.tsx
  packages/plasma-icons/src/Icons/IconSberBoxTopStroke.tsx
  packages/plasma-icons/src/Icons/IconSberPortal.tsx
  packages/plasma-icons/src/Icons/IconSberPortalStroke.tsx
  packages/plasma-icons/src/Icons/IconTvAlt1.tsx
  packages/plasma-icons/src/Icons/IconTvMode.tsx
  packages/plasma-icons/src/Icons/IconTvModeWiFi.tsx
  packages/plasma-icons/src/index.ts
Labels: RFT

#1060 feat(plasma-ui-docs, plasma-web-docs): Added Storybook links on doc p…
  utils/plasma-docs-ui/package-lock.json
  utils/plasma-docs-ui/package.json
  utils/plasma-docs-ui/src/components/GlobalStyle.tsx
  utils/plasma-docs-ui/src/components/Storybook.tsx
  utils/plasma-docs-ui/src/components/index.tsx
  website/plasma-ui-docs/docs/components/Badge.mdx
  website/plasma-ui-docs/docs/components/Button.mdx
  website/plasma-ui-docs/docs/components/Card.mdx
  website/plasma-ui-docs/docs/components/Carousel.mdx
  website/plasma-ui-docs/docs/components/Cell.mdx
  website/plasma-ui-docs/docs/components/Checkbox.mdx
  website/plasma-ui-docs/docs/components/Grid.mdx
  website/plasma-ui-docs/docs/components/Header.mdx
  website/plasma-ui-docs/docs/components/Icon.mdx
  website/plasma-ui-docs/docs/components/Image.mdx
  website/plasma-ui-docs/docs/components/MarkedList.mdx
  website/plasma-ui-docs/docs/components/Marquee.mdx
  website/plasma-ui-docs/docs/components/PaginationDots.mdx
  website/plasma-ui-docs/docs/components/Pickers.mdx
  website/plasma-ui-docs/docs/components/Price.mdx
  website/plasma-ui-docs/docs/components/Radiobox.mdx
  website/plasma-ui-docs/docs/components/Skeleton.mdx
  website/plasma-ui-docs/docs/components/Slider.mdx
  website/plasma-ui-docs/docs/components/Spinner.mdx
  website/plasma-ui-docs/docs/components/Stepper.mdx
  website/plasma-ui-docs/docs/components/Switch.mdx
  website/plasma-ui-docs/docs/components/Tabs.mdx
  website/plasma-ui-docs/docs/components/TextArea.mdx
  website/plasma-ui-docs/docs/components/TextBox.mdx
  website/plasma-ui-docs/docs/components/TextField.mdx
  website/plasma-ui-docs/docs/components/Toast.mdx
  website/plasma-ui-docs/docs/components/Typography.mdx
  website/plasma-ui-docs/src/components/Storybook.tsx
  website/plasma-ui-docs/src/components/index.ts
  website/plasma-web-docs/docs/components/Badge.mdx
  website/plasma-web-docs/docs/components/Button.mdx
  website/plasma-web-docs/docs/components/Carousel.mdx
  website/plasma-web-docs/docs/components/Checkbox.mdx
  website/plasma-web-docs/docs/components/Dropdown.mdx
  website/plasma-web-docs/docs/components/Grid.mdx
  website/plasma-web-docs/docs/components/Image.mdx
  website/plasma-web-docs/docs/components/Link.mdx
  website/plasma-web-docs/docs/components/Modal.mdx
  website/plasma-web-docs/docs/components/Notification.mdx
  website/plasma-web-docs/docs/components/Price.mdx
  website/plasma-web-docs/docs/components/Progress.mdx
  website/plasma-web-docs/docs/components/Radiobox.mdx
  website/plasma-web-docs/docs/components/Select.mdx
  website/plasma-web-docs/docs/components/Skeleton.mdx
  website/plasma-web-docs/docs/components/Spinner.mdx
  website/plasma-web-docs/docs/components/Switch.mdx
  website/plasma-web-docs/docs/components/Tabs.mdx
  website/plasma-web-docs/docs/components/TextArea.mdx
  website/plasma-web-docs/docs/components/TextField.mdx
  website/plasma-web-docs/docs/components/Tooltip.mdx
  website/plasma-web-docs/docs/components/Typography.mdx
  website/plasma-web-docs/src/components/Storybook.tsx
  website/plasma-web-docs/src/components/index.ts
Labels: Docs, TESTING

#1055 feat(plasma-ui): `Picker`: Added `xs` size
  packages/plasma-ui/src/components/Pickers/Picker.tsx
  packages/plasma-ui/src/components/Pickers/PickerDots.tsx
  packages/plasma-ui/src/components/Pickers/PickerItem.tsx
  packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
  packages/plasma-ui/src/components/Pickers/TimePicker.tsx
  packages/plasma-ui/src/components/Pickers/types.ts
  packages/plasma-ui/src/components/Pickers/utils.ts
  website/plasma-ui-docs/docs/components/Pickers.mdx
Labels: UI (Canvas Apps), TESTED

#1069 chore(plasma-web-docs): `TextField`: Incorrect `status` prop usage
  packages/plasma-web/src/components/TextField/TextField.stories.tsx
  website/plasma-web-docs/docs/components/TextField.mdx
Labels: TESTED

#1073 fix(plasma-web): `TextField`: fix `size:l` by providing $size to input
  packages/plasma-web/src/components/TextField/TextField.tsx
Labels: TESTED, B2B/E

#1074 chore(plasma-b2c): `TextField` hide `size` prop in storybook
  packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
Labels: RFT, B2C

#1087 fix(plasma-web, plasma-b2c): `Tooltip`: `dark02` and `white` colors
  cypress/snapshots/b2c/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- interaction.snap.png
  cypress/snapshots/b2c/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- multiple placement.snap.png
  cypress/snapshots/b2c/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- out of bounds.snap.png
  cypress/snapshots/b2c/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- simple.snap.png
  cypress/snapshots/web/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- interaction.snap.png
  cypress/snapshots/web/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- multiple placement.snap.png
  cypress/snapshots/web/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- out of bounds.snap.png
  cypress/snapshots/web/components/Tooltip/Tooltip.component-test.tsx/plasma-web Tooltip -- simple.snap.png
  packages/plasma-web/src/components/Tooltip/Tooltip.tsx
Labels: TESTED, B2B/E, B2C

#1090 fix(plasma-web, plasma-b2c): `TextField`: separated helper spacing st…
  cypress/snapshots/b2c/components/Select/SelectBase.component-test.tsx/plasma-web Select -- disabled.snap.png
  cypress/snapshots/b2c/components/Select/SelectBase.component-test.tsx/plasma-web Select -- empty.snap.png
  cypress/snapshots/b2c/components/Select/SelectBase.component-test.tsx/plasma-web Select -- item click.snap.png
  cypress/snapshots/b2c/components/Select/SelectBase.component-test.tsx/plasma-web Select -- multiselect.snap.png
  cypress/snapshots/b2c/components/Select/SelectBase.component-test.tsx/plasma-web Select -- simple.snap.png
  cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- content.snap.png
  cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- default.snap.png
  cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- disabled.snap.png
  cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- focused.snap.png
  cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- success, warning, error.snap.png
  cypress/snapshots/web/components/Select/Select.component-test.tsx/plasma-web Select -- disabled.snap.png
  cypress/snapshots/web/components/Select/Select.component-test.tsx/plasma-web Select -- empty.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- contentRight.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- default.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- disabled.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- focused.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- resize.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- success, warning, error.snap.png
  cypress/snapshots/web/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- content.snap.png
  cypress/snapshots/web/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- default.snap.png
  cypress/snapshots/web/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- disabled.snap.png
  cypress/snapshots/web/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- focused.snap.png
  cypress/snapshots/web/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- success, warning, error.snap.png
  packages/plasma-core/src/components/Field/Field.tsx
  packages/plasma-ui/src/components/Field/Field.tsx
  packages/plasma-ui/src/components/Field/index.ts
  packages/plasma-ui/src/components/TextArea/TextArea.tsx
  packages/plasma-ui/src/components/TextField/TextField.tsx
Labels: TESTED, B2B/E, B2C

#1088 fix(plasma-b2c): `Editable`: background in light theme
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- empty.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- onBlur and onFocus.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- onPaste.snap.png
  cypress/snapshots/b2c/components/Editable/Editable.component-test.tsx/plasma-b2c Editable -- simple.snap.png
  packages/plasma-b2c/src/components/Editable/Editable.tsx
Labels: TESTED, B2C

#1076 fix(plasma-ui): `HeaderArrow`: made unfocusable
  packages/plasma-ui/src/components/Header/HeaderArrow.tsx
Labels: UI (Canvas Apps), TESTED

#1075 feat(plasma-ui): Made overlay optional for Sheet
  cypress/snapshots/ui/components/Sheet/Sheet.component-test.tsx/closed.snap.png
  cypress/snapshots/ui/components/Sheet/Sheet.component-test.tsx/opened.snap.png
  cypress/snapshots/ui/components/Sheet/Sheet.component-test.tsx/plasma-ui Sheet -- onClose.snap.png
  cypress/snapshots/ui/components/Sheet/Sheet.component-test.tsx/plasma-ui Sheet -- withoutOverlay.snap.png
  packages/plasma-ui/src/components/Sheet/Sheet.component-test.tsx
  packages/plasma-ui/src/components/Sheet/Sheet.stories.tsx
  packages/plasma-ui/src/components/Sheet/Sheet.tsx
Labels: UI (Canvas Apps), TESTED

#1104 fix(plasma-web): `Carousel`: moved style resets to core
  packages/plasma-core/src/components/Carousel/Carousel.tsx
  packages/plasma-web/src/components/Carousel/Carousel.tsx
  packages/plasma-web/src/components/Carousel/index.ts
Labels: RFT, B2B/E

#1115 fix: `Tabs`: removed focus outline in item text
  cypress/snapshots/b2c/components/Tabs/TabsBase.component-test.tsx/plasma-core Tabs -- controller.snap.png
  cypress/snapshots/ui/components/Tabs/Tabs.component-test.tsx/plasma-ui Tabs -- _animated.snap.png
  cypress/snapshots/ui/components/Tabs/TabsBase.component-test.tsx/plasma-core Tabs -- controller.snap.png
  cypress/snapshots/web/components/Tabs/TabsBase.component-test.tsx/plasma-core Tabs -- controller.snap.png
  packages/plasma-core/src/components/Tabs/TabItem.tsx
Labels: TESTED

#1118 fix(plasma-ui): fix slider size and offset when active tab size is changed
  packages/plasma-ui/package-lock.json
  packages/plasma-ui/package.json
  packages/plasma-ui/src/components/Tabs/TabsSlider.tsx
Labels: TESTED

#1114 fix(plasma-core): Use default view for input readonly state
  cypress/snapshots/ui/components/TextField/TextField.component-test.tsx/plasma-core TextField -- readOnly.snap.png
  packages/plasma-core/src/components/Input/Input.mixins.ts
  packages/plasma-core/src/components/TextField/TextField.component-test.tsx
  packages/plasma-ui/src/components/TextField/TextField.stories.tsx
Labels: RFT

#1117 fix(plasma-web): Image ratio fix
  cypress/snapshots/temple@sberbox/pages/GalleryPage/GalleryPage@sberbox.component-test.tsx/GalleryPage -- CustomCard in galleries -- Variable card height.snap.png
  cypress/snapshots/ui/components/Carousel/Carousel.component-test.tsx/plasma-ui Carousel -- music.snap.png
  cypress/snapshots/ui/components/Image/Image.component-test.tsx/plasma-core Image -- _ratio.snap.png
  packages/plasma-core/src/components/Image/Image.tsx
Labels: TESTED

#1112 chore(plasma-ui): Label in `TextBox`'s stories
  packages/plasma-ui/src/components/TextBox/TextBox.stories.tsx
Labels: TESTED
