Repository sberdevices/plasma, pull requests merged in 2022-03, with the labels that each got.

#1108 feat: `PaginationDots`: made `aria-hidden=true` by default
  packages/plasma-core/src/components/PaginationDots/PaginationDots.tsx
Labels: UI (Canvas Apps), TESTING, B2B/E, B2C

#1079 feat(plasma-temple): Product component
  packages/plasma-temple/.storybook/public/images/img.png
  packages/plasma-temple/package-lock.json
  packages/plasma-temple/package.json
  packages/plasma-temple/src/components/Cart/CartItemImage/CartItemImage.tsx
  packages/plasma-temple/src/components/Collapse/Collapse.tsx
  packages/plasma-temple/src/components/Collapse/hooks/useCollapse.ts
  packages/plasma-temple/src/components/Product/Product.stories.tsx
  packages/plasma-temple/src/components/Product/Product.tsx
  packages/plasma-temple/src/components/Product/Product@common.tsx
  packages/plasma-temple/src/components/Product/Product@mobile.tsx
  packages/plasma-temple/src/components/Product/ProductActionButton/ProductActionButton.tsx
  packages/plasma-temple/src/components/Product/ProductCharacteristics/ProductCharacteristics.stories.tsx
  packages/plasma-temple/src/components/Product/ProductCharacteristics/ProductCharacteristics.tsx
  packages/plasma-temple/src/components/Product/ProductDescription/ProductDescription.stories.tsx
  packages/plasma-temple/src/components/Product/ProductDescription/ProductDescription.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ExpandableProductDetails/ExpandableProductDetails.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ExpandableProductDetails/ExpandableProductDetails@common.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ExpandableProductDetails/ExpandableProductDetails@mobile.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ProductDetails.stories.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ProductDetails.tsx
  packages/plasma-temple/src/components/Product/ProductDetails/ProductDetailsItem/ProductDetailsItem.tsx
  packages/plasma-temple/src/components/Product/ProductImage/ProductImage.stories.tsx
  packages/plasma-temple/src/components/Product/ProductImage/ProductImage.tsx
  packages/plasma-temple/src/components/Product/ProductImageSlider/ProductImageSlider.stories.tsx
  packages/plasma-temple/src/components/Product/ProductImageSlider/ProductImageSlider.tsx
  packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo.stories.tsx
  packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo.tsx
  packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo@common.tsx
  packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo@mobile.tsx
  packages/plasma-temple/src/components/Product/ProductPageSmamokat.stories.tsx
  packages/plasma-temple/src/components/Product/ProductPageSmartHome.stories.tsx
  packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice.tsx
  packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice@common.tsx
  packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice@sberbox.tsx
  packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice@sberportal.tsx
  packages/plasma-temple/src/components/Product/ProductPrice/types.ts
  packages/plasma-temple/src/components/Product/ProductRecommendations/ProductRecommendations.stories.tsx
  packages/plasma-temple/src/components/Product/ProductRecommendations/ProductRecommendations.tsx
  packages/plasma-temple/src/components/Product/ProductRecommendations/ProductRecommendationsItem/ProductRecommendationsItem.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@mobile.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@sberbox.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@sberportal.tsx
  packages/plasma-temple/src/components/Product/ProductToggleButton/ProductToggleButton.tsx
  packages/plasma-temple/src/components/Product/ProductVariationSwitcher/ProductVariationItem/ProductVariationItem.tsx
  packages/plasma-temple/src/components/Product/ProductVariationSwitcher/ProductVariationSwitcher.stories.tsx
  packages/plasma-temple/src/components/Product/ProductVariationSwitcher/ProductVariationSwitcher.tsx
  packages/plasma-temple/src/components/Product/hooks/useScrollByBreakpoints.ts
  packages/plasma-temple/src/components/Product/index.ts
  packages/plasma-temple/src/components/Product/types.ts
  packages/plasma-temple/src/hooks/useWindowInnerWidth.ts
  packages/plasma-temple/src/utils/getScreenScrollBreakpoints.ts
  packages/plasma-temple/src/utils/isElementOutViewport.ts
Labels: RFT

#1120 fix(plasma-ui): `TimePicker` splitter size
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker -- _size.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker -- change values by click.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker -- default.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker -- without infiniteScroll.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- change values with max.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- change values with min.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- change values.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- with controls.snap.png
  packages/plasma-ui/src/components/Pickers/PickerDots.tsx
  packages/plasma-ui/src/components/Pickers/PickerItem.tsx
  packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
  packages/plasma-ui/src/components/Pickers/TimePicker.component-test.tsx
Labels: TESTED

#1138 fix(plasma-web-docs): Docusaurus docgen plugin's json fail
  website/plasma-web-docs/docusaurus.config.js
Labels: Docs

#1136 chore(plasma-web): Delete `Popup` from storybook
  packages/plasma-web/src/components/Popup/Popup.stories.tsx
Labels: RFT, B2B/E

#1128 feat(plasma-temple): error page improvements and mobile version
  cypress/snapshots/temple@mobile/pages/ErrorPage/ErrorPage@mobile.component-test.tsx/ErrorPage -- render -- after each hook.snap.png
  cypress/snapshots/temple@mobile/pages/ErrorPage/ErrorPage@mobile.component-test.tsx/ErrorPage -- render without any controls -- after each hook.snap.png
  cypress/snapshots/temple@mobile/pages/ErrorPage/ErrorPage@mobile.component-test.tsx/ErrorPage -- render without message and with buttons as ReactNode -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render with broken image -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render with children -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render without any controls -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render without message and with buttons as ReactNode -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/ErrorPage/ErrorPage@sberbox.component-test.tsx/ErrorPage -- render and button focuced -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/ErrorPage/ErrorPage@sberbox.component-test.tsx/ErrorPage -- render without message and with buttons as ReactNode -- after each hook.snap.png
  cypress/snapshots/temple@sberbox/pages/OrderSuccessPage/OrderSuccessPage@common.component-test.tsx/OrderSuccessPage -- render without image.snap.png
  cypress/snapshots/temple@sberbox/pages/OrderSuccessPage/OrderSuccessPage@common.component-test.tsx/OrderSuccessPage -- render.snap.png
  cypress/snapshots/temple@sberportal/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render with broken image -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/components/StateLayout/StateLayout@common.component-test.tsx/StateLayout -- render with children -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render without any controls -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/pages/ErrorPage/ErrorPage@common.component-test.tsx/ErrorPage -- render without message and with buttons as ReactNode -- after each hook.snap.png
  cypress/snapshots/temple@sberportal/pages/OrderSuccessPage/OrderSuccessPage@common.component-test.tsx/OrderSuccessPage -- render without image.snap.png
  cypress/snapshots/temple@sberportal/pages/OrderSuccessPage/OrderSuccessPage@common.component-test.tsx/OrderSuccessPage -- render.snap.png
  packages/plasma-temple/.storybook/public/images/error.svg
  packages/plasma-temple/.storybook/public/images/placeholder.svg
  packages/plasma-temple/.storybook/public/images/success.svg
  packages/plasma-temple/src/components/FullScreenBackgroundWrapper/FullScreenBackgroundWrapper.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout.stories.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout@common.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout@mobile.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout@sberbox.tsx
  packages/plasma-temple/src/components/StateLayout/StateLayout@sberportal.tsx
  packages/plasma-temple/src/components/StateLayout/hooks/useImageToRender.tsx
  packages/plasma-temple/src/components/StateLayout/types.ts
  packages/plasma-temple/src/hooks/useWindowInnerHeight.ts
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage.stories.tsx
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage.tsx
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage@common.component-test.tsx
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage@helpers.component-test.tsx
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage@mobile.component-test.tsx
  packages/plasma-temple/src/pages/ErrorPage/ErrorPage@sberbox.component-test.tsx
  packages/plasma-temple/src/pages/OrderSuccessPage/OrderSuccessPage@common.component-test.tsx
  website/plasma-temple-docs/docs/components/StateLayout.mdx
Labels: TESTED

#1081 fix(plasma-ui): Update `Picker` infinite scroll behavior
  cypress/snapshots/temple@sberbox/components/Form/Form@common.component-test.tsx/Form -- different types of fields -- render.snap.png
  cypress/snapshots/temple@sberportal/components/Form/Form@common.component-test.tsx/Form -- different types of fields -- render.snap.png
  cypress/snapshots/ui/components/Pickers/DatePicker.component-test.tsx/plasma-ui DatePicker -- default.snap.png
  cypress/snapshots/ui/components/Pickers/DatePicker.component-test.tsx/plasma-ui DatePicker -- with controls.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker -- default.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- change values with max.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- change values with min.snap.png
  cypress/snapshots/ui/components/Pickers/TimePicker.component-test.tsx/plasma-ui TimePicker update value -- with controls.snap.png
  packages/plasma-core/src/components/Carousel/hooks.tsx
  packages/plasma-core/src/components/Carousel/types.tsx
  packages/plasma-ui/src/components/Carousel/Carousel.tsx
  packages/plasma-ui/src/components/Pickers/DatePicker.component-test.tsx
  packages/plasma-ui/src/components/Pickers/Picker.tsx
  packages/plasma-ui/src/components/Pickers/PickerItem.tsx
  packages/plasma-ui/src/components/Pickers/TimePicker.component-test.tsx
  packages/plasma-ui/src/components/Pickers/hooks.ts
Labels: UI (Canvas Apps), TESTING, Core

#1147 feat(versionate-docs): Added versionArchived.json sort
  actions/versionate-docs/package-lock.json
  actions/versionate-docs/package.json
  actions/versionate-docs/src/fs.ts
  actions/versionate-docs/src/utils.test.ts
  actions/versionate-docs/src/utils.ts
Labels: CI

#1134 docs: `Spinner` live example of a11y
  packages/plasma-web/src/components/Spinner/Spinner.stories.tsx
Labels: TESTED, B2B/E, A11Y

#1129 docs: `withSkeleton` wraps component with a11y
  packages/plasma-web/src/components/Skeleton/Skeleton.stories.tsx
  website/plasma-web-docs/docs/components/Skeleton.mdx
Labels: Docs, TESTED, B2B/E, A11Y

#1135 feat(plasma-web): `Tooltip` a11y & close with esc
  packages/plasma-web/src/components/Tooltip/Tooltip.stories.mdx
  packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx
  packages/plasma-web/src/components/Tooltip/Tooltip.tsx
Labels: TESTED, B2B/E, A11Y

#1143 feat(plasma-temple): Item component
  cypress/fixtures/images/cat.png
  cypress/snapshots/temple@mobile/components/Item/Item@mobile.component-test.tsx/Item -- render item with entities carousel.snap.png
  cypress/snapshots/temple@mobile/components/Item/Item@mobile.component-test.tsx/Item -- render item.snap.png
  cypress/snapshots/temple@mobile/components/Item/Item@mobile.component-test.tsx/Item -- render without background.snap.png
  cypress/snapshots/temple@sberbox/components/Item/Item@common.component-test.tsx/Item -- render item with entities carousel.snap.png
  cypress/snapshots/temple@sberbox/components/Item/Item@common.component-test.tsx/Item -- render item.snap.png
  cypress/snapshots/temple@sberbox/components/Item/Item@common.component-test.tsx/Item -- render without background.snap.png
  cypress/snapshots/temple@sberbox/pages/ItemPage/itemPage@sberbox.component-test.tsx/ItemPage -- base test -- screen rendered.snap.png
  cypress/snapshots/temple@sberbox/pages/ItemPage/itemPage@sberbox.component-test.tsx/ItemPage -- render with custom card -- render list of custom card.snap.png
  cypress/snapshots/temple@sberportal/components/Item/Item@common.component-test.tsx/Item -- render item with entities carousel.snap.png
  cypress/snapshots/temple@sberportal/components/Item/Item@common.component-test.tsx/Item -- render item.snap.png
  cypress/snapshots/temple@sberportal/components/Item/Item@common.component-test.tsx/Item -- render without background.snap.png
  packages/plasma-temple/src/components/FullScreenBackground/FullScreenBackground.tsx
  packages/plasma-temple/src/components/FullScreenBackgroundWrapper/FullScreenBackgroundWrapper.tsx
  packages/plasma-temple/src/components/Item/Item.stories.tsx
  packages/plasma-temple/src/components/Item/Item.tsx
  packages/plasma-temple/src/components/Item/Item@common.component-test.tsx
  packages/plasma-temple/src/components/Item/Item@helpers.component-test.tsx
  packages/plasma-temple/src/components/Item/Item@mobile.component-test.tsx
  packages/plasma-temple/src/components/Item/ItemBackground/ItemBackground.tsx
  packages/plasma-temple/src/components/Item/ItemBackground/ItemBackground@common.tsx
  packages/plasma-temple/src/components/Item/ItemBackground/ItemBackground@mobile.tsx
  packages/plasma-temple/src/components/Item/ItemDetails/ItemDetails.stories.tsx
  packages/plasma-temple/src/components/Item/ItemDetails/ItemDetails.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntities.stories.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntities.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntities@common.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntities@mobile.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntity/ItemEntity.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntity/ItemEntity@common.tsx
  packages/plasma-temple/src/components/Item/ItemEntities/ItemEntity/ItemEntity@mobile.tsx
  packages/plasma-temple/src/components/Item/ItemMainSection/ItemMainSection.tsx
  packages/plasma-temple/src/components/Item/index.ts
  packages/plasma-temple/src/components/Item/types.ts
  packages/plasma-temple/src/components/Product/ProductRecommendations/ProductRecommendationsItem/ProductRecommendationsItem.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@mobile.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@sberbox.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle@sberportal.tsx
  packages/plasma-temple/src/components/Product/ProductTitle/types.ts
  packages/plasma-temple/src/pages/GridPage/GridPage.tsx
  packages/plasma-temple/src/pages/ItemPage/ItemPage.tsx
  packages/plasma-temple/src/pages/ItemPage/components/FullScreenBackground/FullScreenBackground.tsx
  packages/plasma-temple/src/pages/ItemPage/components/ItemEntities/ItemEntities.tsx
  packages/plasma-temple/src/pages/ItemPage/components/ItemEntity/ItemEntity.tsx
  packages/plasma-temple/src/pages/ItemPage/components/ItemMainSection/ItemMainSection.tsx
  packages/plasma-temple/src/pages/ItemPage/components/ItemMainSection/ItemMainSection@sberbox.tsx
  packages/plasma-temple/src/pages/ItemPage/components/ItemMainSection/ItemMainSection@sberportal.tsx
  packages/plasma-temple/src/pages/ItemPage/index.ts
  packages/plasma-temple/src/pages/ItemPage/itemPage@sberbox.component-test.tsx
  packages/plasma-temple/src/pages/ItemPage/types.ts
  packages/plasma-temple/src/registry/registry@sberbox.ts
  packages/plasma-temple/src/registry/registry@sberportal.ts
  packages/plasma-temple/src/registry/types.ts
  packages/plasma-temple/src/types.ts
  website/plasma-temple-docs/docs/components/Item.mdx
Labels: TESTED

#1145 feat(plasma-temple): Success page
  cypress/snapshots/temple@mobile/pages/SuccessPage/SuccessPage@mobile.component-test.tsx/SuccessPage -- render success page with buttons.snap.png
  cypress/snapshots/temple@mobile/pages/SuccessPage/SuccessPage@mobile.component-test.tsx/SuccessPage -- render success page.snap.png
  cypress/snapshots/temple@sberbox/pages/SuccessPage/SuccessPage@common.component-test.tsx/SuccessPage -- render success page with buttons.snap.png
  cypress/snapshots/temple@sberbox/pages/SuccessPage/SuccessPage@common.component-test.tsx/SuccessPage -- render success page.snap.png
  cypress/snapshots/temple@sberportal/pages/SuccessPage/SuccessPage@common.component-test.tsx/SuccessPage -- render success page with buttons.snap.png
  cypress/snapshots/temple@sberportal/pages/SuccessPage/SuccessPage@common.component-test.tsx/SuccessPage -- render success page.snap.png
  packages/plasma-temple/src/hooks/useFocusOnMount.ts
  packages/plasma-temple/src/pages/SuccessPage/SuccessPage.assets/success.svg
  packages/plasma-temple/src/pages/SuccessPage/SuccessPage.stories.tsx
  packages/plasma-temple/src/pages/SuccessPage/SuccessPage.tsx
  packages/plasma-temple/src/pages/SuccessPage/SuccessPage@common.component-test.tsx
  packages/plasma-temple/src/pages/SuccessPage/SuccessPage@mobile.component-test.tsx
  website/plasma-temple-docs/docs/pages/ErrorPage.mdx
  website/plasma-temple-docs/docs/pages/SuccessPage.mdx
  website/plasma-temple-docs/docs/pages/_category_.json
Labels: TESTED
